workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true
controller:
  workflowNamespaces:
    - "argo-workflows"
server:
  extraArgs:
    - --auth-mode=server
  ingress:
    enabled: false
# TODO: implement minio
# artifactRepository:
#  s3: {}
